POST http://localhost:5000/api/perfilFarmacia/registrar HTTP/1.1
content-type: application/json

{
    "nombreUsuario":"Farmacia La Bomba",
    "email": "rando11@email.com",
    "password": "A",
    "rol": "Farmacia"
}